### PR TITLE
initial pre-commit config

### LINKED ISSUE #260: add automation for consistent formatting and linting
Consistently formatted yaml, json, etc makes it easier for multiple developers and reduces git diffs.

Formatting and linting that can be run on at git commit time with a git hook, reduces the need for this later in PRs (Github action can be used to confirms that it was done)

There are tools to manage pre-commit hooks like: 

* https://pre-commit.com
* https://typicode.github.io/husky/how-to.html

Since this project is a multilingual project:

```
❯ tokei -C --sort lines
===============================================================================
 Language            Files        Lines         Code     Comments       Blanks
===============================================================================
 HTML                  136        94823        55057            0        39766
 YAML                 1146        93645        81165         2961         9519
 Ruby                   34        16690        11701         2340         2649
 JSON                   12         5883         5855            0           28
 JavaScript              7         4158         4096            9           53
 Ruby HTML              20         3001         2668            0          333
 Rakefile               10         1914         1582           38          294
 AsciiDoc                7         1816         1397            0          419
 CSS                     3          556          512            7           37
 BASH                    9          219          165           16           38
 Module-Definition       1           37           25            0           12
 Markdown                1            1            0            1            0
===============================================================================
 Total                1386       222743       164223         5372        53148
===============================================================================
```

I would suggest using pre-commit to manage the hooks but I'm open to exploring other tooling. (I do realize that since pre-commit is python based I'd be adding another language to the dev dependencies)

I'm happy to put in a PR once the discussion done.

### PR DESCRIPTION
**Pull request by kbroch-rivosinc**
soft launch meaning only people with pre-commit tool installed would see this run. (full launch would entail, running pre-commit on all files to clean up past and  github action to enforce pre-commit)

If you want to see full effect on files run: `pre-commit run --all-files` I looked the results of this over and changes seem fine.

There's a lot of formatting changes to the html. (but some of the html looks minified so to be expected) I'd suggest maintainers look over what the changes would be for all the files and the generate final docs.

fixes #260

### CODE REVIEW

**Comment by dhower-qc** [comment]
check out #270, which adds "./bin/pre-commit" to run pre-commit regardless of whether you are using a devcontainer or singularity

**Comment by dhower-qc** [comment]
we should ignore everything in `docs/ruby`. those are all generated files

**Comment by dhower-qc** [comment]
Can pre-commit check for Unicode characters? A common problem is when a cut/paste from, e.g., the ISA manual, brings in Unicode to the YAML. That sometimes messes with the tools.

**Comment by kbroch-rivosinc** [comment]
> Can pre-commit check for Unicode characters? A common problem is when a cut/paste from, e.g., the ISA manual, brings in Unicode to the YAML. That sometimes messes with the tools.

The default `check-yaml` https://github.com/pre-commit/pre-commit-hooks/blob/main/pre_commit_hooks/check_yaml.py#L11 does a load of the yaml file.  Would this detect that problem?

**Comment by dhower-qc** [comment]
It might, but I'm not sure. The problem arises when we try to load a YAML file with non-ASCII characters using the standard Ruby YAML library (which itself is just a wrapper around the C libyaml library). It will fail, but unfortunately without a helpful error message.

I see that the library used by pre-commit -- ruamel.yaml -- has some pretty cool features like key order preservation and comment preservation. It could be a part of a solution to the "scripting changes" problem I've been concerned about.

It's easy enough to make a little script to check for Unicode. Probably easier to do that then search around for something turn-key ready. How about this: **I'll make the script and you figure out how to run it from pre-commit?**

**Comment by kbroch-rivosinc** [comment]
> It might, but I'm not sure. The problem arises when we try to load a YAML file with non-ASCII characters using the standard Ruby YAML library (which itself is just a wrapper around the C libyaml library). It will fail, but unfortunately without a helpful error message.

I think we might need to discuss this more.  My concern is YAML and AsciiDoc are both fully capable of supporting unicode and given these are the "docs" putting the ascii only restriction on the content seems problematic, especially if we want to support tooling that could be used to generate docs in other languages.

**Comment by kbroch-rivosinc** [comment]
@dhower-qc : this PR should be good to go as we discussed.  Broke up into 2 commit: one for hooks added, one for autofix changes from those hooks

**Comment by dhower-qc** [comment]
When I try this, pre-commit doesn't seem to do anything:

```
hu-dhower-lv:riscv-unified-db-3 (65) ./bin/pre-commit 
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
check for broken symlinks............................(no files to check)Skipped
fix end of files.....................................(no files to check)Skipped
trim trailing whitespace.............................(no files to check)Skipped
```

Same with `pre-commit run --all-files`. Is this the expected output?

**Comment by kbroch-rivosinc** [comment]
> 
> Same with `pre-commit run --all-files`. Is this the expected output?

No after you pulled in 2f735f8795618a11c4dffc02d6b119102c57a83f you should have seen this: 

```
❯ pre-commit run --all-file
check for broken symlinks............................(no files to check)Skipped
fix end of files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing arch/csr/mhartid.yaml
Fixing arch/csr/mip.yaml
Fixing arch/isa/fp.idl

trim trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing schemas/csr_schema.json
Fixing lib/test/test_yaml_loader.rb
Fixing arch/csr/mip.yaml
Fixing arch/csr/mie.yaml
```

But I'm not running `pre-commit` from the container.

**Review by dhower-qc — APPROVED** [review]

**Pull request merged**
