### PR TITLE
Add dockerFile support

### PR DESCRIPTION
**Pull request by AFOliveira**
As discussed on last meeting that dockerfile could ease user interaction with the UDB, I came up with this dockerfile which runs with the following:

sudo docker build -t udb -f .devcontainer/Dockerfile .
sudo docker run -it -v $(pwd):/workspace -w /workspace udb bash

I could add an environment variable to ensure easier interaction with ./do since I have not touched that part.

### CODE REVIEW

**Comment by kbroch-rivosinc** [comment]
This worked well for me on mac. Only thing I had to do first was:

```
❯ docker pull ubuntu:24.04
24.04: Pulling from library/ubuntu
Digest: sha256:80dd3c3b9c6cecb9f1667e9290b3bc61b78c2678c02cbdae5f0fea92cc6734ab
Status: Image is up to date for ubuntu:24.04
docker.io/library/ubuntu:24.04

What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview ubuntu:24.04
```

Because the `sudo docker build` couldn't access the credentials.

After that I did the `sudo docker run` and was able to run the `./do` commands including `./do smoke`

**Review by kbroch-rivosinc — APPROVED** [review]

**Comment by dhower-qc** [comment]
Excellent!

- Why did you merge the apt commands into a single line? I though best practice was to keep them separate so that Docker can layer the image better.
- Let's get this published to DockerHub so most people won't have to build. The singularity container is here: https://hub.docker.com/r/riscvintl/spec-generator. @rpsene, can you help us here? We'll need a place to put a x86 Docker image and an AArch64 Docker image.
- Let's get this working with the scripts under `bin/`. I'm thinking we could store a selector (singularity/docker) on first run, and the use it to pick which one to use from then on. The changes should be isolated to `bin/setup`. @AFOliveira, is that something you can take on? We can set up a quick call to talk it through if you want.

**Comment by AFOliveira** [comment]
The answer to this 

> Why did you merge the apt commands into a single line? 

is my ignorance on this :) , but I'll modify it back.

> best practice was to keep them separate so that Docker can layer the image better


> Let's get this working with the scripts under bin/. I'm thinking we could store a selector (singularity/docker) on first run, and the use it to pick which one to use from then on. The changes should be isolated to bin/setup. @AFOliveira, is that something you can take on? We can set up a quick call to talk it through if you want

I can surely do  it. Actually, I've kind of already done this, the way I implemented it was by setting an environment variable and just 

`export docker=1` 

and then messed around a bit with the scripts under /bin. I'll push a new commit with what I've done so far, so you can review it and maybe then we can schedule a call and discuss how to do it?

**Comment by rpsene** [comment]
@dhower-qc @AFOliveira https://github.com/riscv-software-src/riscv-unified-db/pull/351

**Comment by AFOliveira** [comment]
FYI: I messed up the last commits, I'm fixing it.

**Comment by AFOliveira** [comment]
@dhower-qc can you please write how you want this docker or specify to be done? I understood it was though a config, but what would that flow look like?

**Comment by rpsene** [comment]
@AFOliveira take a look here: https://github.com/riscv-software-src/riscv-unified-db/pull/351

I will update that PR this week.

**Comment by AFOliveira** [comment]
> @AFOliveira take a look here: #351
> 
> I will update that PR this week.

Thanks (or obrigado :) ) for the pointer, Rafael. I'll be paying attention to your PR.

**Review by dhower-qc — APPROVED** [review]
@AFOliveira, I added a prompt if DOCKER/SINGULARITY env variables aren't present, and updated the regression accordingly. I also changed the Docker run command to map the UDB ROOT directly instead of $pwd (which all the scripts are assuming). Let me know if you see any issues. Otherwise, this is good to go.

**Comment by AFOliveira** [comment]
Sorry for not understanding what you were asking in first place and thanks for the help on this :).

**Review by AFOliveira — COMMENTED** [review]
I just tested and all worked as supposed!

**Comment by AFOliveira** [comment]
@dhower-qc github pages deployment failed, did I mess this up?

**Pull request merged**
