### PR TITLE
Add V extension missing isntructions

### PR DESCRIPTION
**Pull request by AFOliveira**
Solves #314

### CODE REVIEW

**Comment by AFOliveira** [comment]
@BrianAnakPintar Have you checked if I managed to cover all instructions?

**Comment by BrianAnakPintar** [comment]
Yup I just ran it, seems like in terms of V instructions it works perfectly. 

The main issues now are just the extensions and variable fields. I think I might have an idea how to tackle these so I'll try to resolve these first.

There is also however another batch of missing instruction here are all of them that I found when using the latest `riscv-opcodes`:
```json
    "cm_jalt": {
        "encoding": "----------------101000--------10",
        "variable_fields": [
            "c_index"
        ],
        "extension": [
            "rv_zcmt"
        ],
        "match": "0xa002",
        "mask": "0xfc03"
    },
    "cm_mva01s": {
        "encoding": "----------------101011---11---10",
        "variable_fields": [
            "c_sreg1",
            "c_sreg2"
        ],
        "extension": [
            "rv_zcmp"
        ],
        "match": "0xac62",
        "mask": "0xfc63"
    },
    "cm_mvsa01": {
        "encoding": "----------------101011---01---10",
        "variable_fields": [
            "c_sreg1",
            "c_sreg2"
        ],
        "extension": [
            "rv_zcmp"
        ],
        "match": "0xac22",
        "mask": "0xfc63"
    },
    "cm_pop": {
        "encoding": "----------------10111010------10",
        "variable_fields": [
            "c_rlist",
            "c_spimm"
        ],
        "extension": [
            "rv_zcmp"
        ],
        "match": "0xba02",
        "mask": "0xff03"
    },
    "cm_popret": {
        "encoding": "----------------10111110------10",
        "variable_fields": [
            "c_rlist",
            "c_spimm"
        ],
        "extension": [
            "rv_zcmp"
        ],
        "match": "0xbe02",
        "mask": "0xff03"
    },
    "cm_popretz": {
        "encoding": "----------------10111100------10",
        "variable_fields": [
            "c_rlist",
            "c_spimm"
        ],
        "extension": [
            "rv_zcmp"
        ],
        "match": "0xbc02",
        "mask": "0xff03"
    },
    "cm_push": {
        "encoding": "----------------10111000------10",
        "variable_fields": [
            "c_rlist",
            "c_spimm"
        ],
        "extension": [
            "rv_zcmp"
        ],
        "match": "0xb802",
        "mask": "0xff03"
    },
```

**Comment by dhower-qc** [comment]
@ayosher, are you working on these Zc instructions?

**Comment by ayosher** [comment]
Zcmp and Zcmt are in my todo list. Not added yet, will take some time (pretty busy these days)

**Comment by AFOliveira** [comment]
@BrianAnakPintar BTW if you need any help in this

> The main issues now are just the extensions and variable fields. I think I might have an idea how to tackle these so I'll try to resolve these first.

LMK directly or open a issue here in the UDB, your feedback might be really important in terms of us figuring out the exact format of instructions

**Pull request merged**
