### PR TITLE
Created common base class called "Portfolio" that both Profiles and CRDs use.

### PR DESCRIPTION
**Pull request by james-ball-qualcomm**
This is for #58

### CODE REVIEW

**Comment by james-ball-qualcomm** [comment]
Looks ready to merge into main if you approve.

**Review by dhower-qc — CHANGES_REQUESTED** [review]
How does this relate to #242?

**Comment by james-ball-qualcomm** [comment]
I made the 3 commits for this PR and then did 2 more commits (in a new branch off main #238) and then did a PR for it (#242). Since the first PR (#241) wasn't merged into main when I created branch #238, I had to merge the commits from #241 into #238 (so it has 5 commits). BTW, I wanted to ask you how to best handle this situation. What I did for my current branch is to base it off the branch #238 and that was nice because all 5 commits we already present in my workspace.

**Comment by james-ball-qualcomm** [comment]
Can you merge this?

**Review by dhower-qc — APPROVED** [review]

**Pull request merged**
