### PR TITLE
Schema change

### LINKED ISSUE #246: Make name and kind explicit in objects
Need to update Ruby code, too.

### PR DESCRIPTION
**Pull request by dhower-qc**
fixes #246

### CODE REVIEW

**Review by james-ball-qualcomm — CHANGES_REQUESTED** [review]
Why do I only see changes to one certificate_model? Shouldn't this change require all the certificate arch files (models & classes) and profile arch files (releases & classes) to be changed?

**Review by james-ball-qualcomm — CHANGES_REQUESTED** [review]
The examples in arch/README.adoc need to be updated.

**Review by james-ball-qualcomm — CHANGES_REQUESTED** [review]
Why did you rename MockCertificateModel to MockCertificateModel100? I don't want to hold up merging this into main but I am curious why the change (and somewhat concerned).

**Review by james-ball-qualcomm — APPROVED** [review]

**Comment by james-ball-qualcomm** [comment]
I'm going to restore the original name of MockCertificateModel.

Also, I noticed that there is no Profile schema and the Profile Release and Profile Class haven't been updated yet. Is that on your list to change relatively soon?

**Comment by james-ball-qualcomm** [comment]
What happened to these tests in test_yaml_loader.rb? Why were they removed? Were they renamed or moved somewhere else?

def test_refs_in_the_same_document
    yaml = <<~YAML
      $defs:
        target1: A string
        target2:
          a: hash

      obj1:
        $ref: "#/$defs/target2"

      obj2:
        $ref: "#/$defs/target2"
        target2: Should disappear

      obj3:
        target2: Should disappear
        $ref: "#/$defs/target2"

    YAML

    f = Tempfile.new("yml")
    f.write(yaml)
    f.flush

    doc = YamlLoader.load(f.path)
    assert_equal({ "a" => "hash" }, doc["obj1"])
    assert_equal({ "a" => "hash" }, doc["obj2"])
    assert_equal({ "a" => "hash" }, doc["obj3"])
  end

  def test_refs_in_the_different_document
    yaml1 = <<~YAML
      $defs:
        target1: A string
        target2:
          a: hash
    YAML

    f1 = Tempfile.new("yml")
    f1.write(yaml1)
    f1.flush
    f1_path = Pathname.new(f1.path)

    yaml2 = <<~YAML
      obj1:
        $ref: "#{f1_path.basename}#/$defs/target2"

      obj2:
        $ref: "#{f1_path.basename}#/$defs/target2"
        target2: Should disappear

      obj3:
        target2: Should disappear
        $ref: "#{f1_path.basename}#/$defs/target2"
    YAML

    f2 = Tempfile.new("yml")
    f2.write(yaml2)
    f2.flush

    doc = YamlLoader.load(f2.path)
    assert_equal({ "a" => "hash" }, doc["obj1"])
    assert_equal({ "a" => "hash" }, doc["obj2"])
    assert_equal({ "a" => "hash" }, doc["obj3"])
  end

**Comment by dhower-qc** [comment]
We aren't expanding $ref any more; just $inherits.

**Comment by james-ball-qualcomm** [comment]
Thanks. Can you explain how $ref works now vs. before? Also, do we still need all the code for $ref in yaml_loader.rb?

**Pull request merged**
